name: RewardVoting
version: 8.0
main: votepackage.Main
description: Reward your players for voting.
depend: [Votifier]

commands:
    rewardvoting:
        usage: /<command>
        aliases: rv
        description: The rewardvoting base command.
    vote:
        usage: /<command>
        aliases: votesites
        description: Shows the available vote websites.
    test:
        usage: /<command>
        description: Rewardvoting developer testing command.